FROM ubuntu:14.04
MAINTAINER Eduardo Hattori <eduardo.hattori@hotmail.com>

#Update Enviroment
RUN apt-get update \
	&& apt-get install -y libaio1 \
	&& apt-get install -y unzip \
	&& apt-get install -y curl \
	&& apt-get install -y nano \
	&& apt-get install -y telnet 

#Install NodeJS
RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
RUN apt-get install -y nodejs

#Create Folder Project
WORKDIR /home
RUN mkdir project
WORKDIR /home/project

#Install PM2
RUN npm install pm2 -g

#Install Mocha
RUN npm install mocha -g

#Install Istanbul
RUN npm install istanbul -g

#Config the start.sh for Initialize the Application
ADD start.sh /
RUN chmod 755 /start.sh
CMD /start.sh;bash

#Port 
EXPOSE 8001